// app/layout.tsx

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ToastProvider } from '@/contexts/ToastContext';
import Script from 'next/script';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';

const inter = Inter({ subsets: ['latin'] });

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'JOK in the Box',
    description: 'JOK in the Box mobile app'
  };
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <head>
        <Script id='viewport-script' strategy='beforeInteractive'>
          {`
            const viewport = document.createElement('meta');
            viewport.name = "viewport";
            viewport.content = "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no";
            document.getElementsByTagName('head')[0].appendChild(viewport);
          `}
        </Script>

        {/* Telegram Mini Apps Analytics Script */}
        <Script src='https://tganalytics.xyz/index.js' strategy='afterInteractive' />

        {/* Initialize Telegram Analytics */}
        <Script id='telegram-analytics-init' strategy='afterInteractive'>
          {`
            function initTelegramAnalytics() {
              const token = '${process.env.NEXT_PUBLIC_TELEGRAM_ANALYTICS}';
              const appName = '${process.env.NEXT_PUBLIC_TELEGRAM_ANALYTICS_NAME}';
              
              if (!token || !appName) {
                console.warn('Telegram Analytics: Missing token or app name in environment variables');
                return;
              }
              
              if (typeof window !== 'undefined' && window.telegramAnalytics) {
                window.telegramAnalytics.init({
                  token: token,
                  appName: appName,
                });
                console.log('Telegram Analytics initialized successfully');
              } else {
                // Retry after a short delay if the library isn't loaded yet
                setTimeout(initTelegramAnalytics, 100);
              }
            }
            
            // Start initialization
            initTelegramAnalytics();
          `}
        </Script>
      </head>
      <body className={inter.className}>
        <Script src='https://static.sonartech.io/lib/1.0.0/sonar.js?appId=app_ac373534' strategy='beforeInteractive' />
        <NextIntlClientProvider messages={messages}>
          <ToastProvider>{children}</ToastProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
