export enum ShopCategory {
  AVATAR = "AVATAR",
  BACKGROUND = "BACKGROUND",
  BOOST = "BOOST",
  OTHERS = "OTHERS",
}

export const shopItems = [
  {
    name: "ClassicJoker",
    description: "ClassicJokerDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character1",
    isBasic: true,
    level: 1,
  },
  {
    name: "Harley",
    description: "HarleyDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character1_harley",
    isBasic: true,
    level: 1,
  },
  {
    name: "Apprentice",
    description: "ApprenticeDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character2",
    isBasic: true,
    level: 2,
  },
  {
    name: "Jester",
    description: "JesterDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character3",
    isBasic: true,
    level: 3,
  },
  {
    name: "Trickster",
    description: "TricksterDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character4",
    isBasic: true,
    level: 4,
  },
  {
    name: "Clown",
    description: "ClownDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character5",
    isBasic: true,
    level: 5,
  },
  {
    name: "CyberArmor",
    description: "CyberArmorDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character6",
    isBasic: true,
    level: 6,
  },
  {
    name: "Cyborg",
    description: "CyborgDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character7",
    isBasic: true,
    level: 7,
  },
  {
    name: "Mastermind",
    description: "MastermindDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character8",
    isBasic: true,
    level: 8,
  },
  {
    name: "Sorcerer",
    description: "SorcererDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character9",
    isBasic: true,
    level: 9,
  },
  {
    name: "Magician",
    description: "MagicianDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character10",
    isBasic: true,
    level: 10,
  },
  {
    name: "Lucky",
    description: "LuckyDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character11",
    isBasic: true,
    level: 11,
  },
  {
    name: "President",
    description: "PresidentDescription",
    category: ShopCategory.AVATAR,
    price: 0,
    image: "character12",
    isBasic: true,
    level: 12,
  },
  // Premium Avatars
  {
    name: "Batman",
    description: "BatmanDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "batman",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Cat",
    description: "CatDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "cat",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "DarthVader",
    description: "DarthVaderDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "darthVader",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Hulk",
    description: "HulkDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "hulk",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Ironman",
    description: "IronmanDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "ironman",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Luffy",
    description: "LuffyDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "luffy",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "MickeyMouse",
    description: "MickeyMouseDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "mickeyMouse",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Naruto",
    description: "NarutoDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "naruto",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Pikachu",
    description: "PikachuDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "pikachu",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "SonGoku",
    description: "SonGokuDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "sonGoku",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Spiderman",
    description: "SpidermanDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "spiderman",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Superman",
    description: "SupermanDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "superman",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Thor",
    description: "ThorDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "thor",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "CyborgHarley",
    description: "CyborgHarleyDescription",
    category: ShopCategory.AVATAR,
    price: 500,
    image: "cyborgHarley",
    isBasic: false,
    invoiceUrl: "",
  },
  // Classic Wallpapers
  {
    name: "DesertedCity",
    description: "DesertedCityDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper1",
    isBasic: true,
    level: 1,
  },
  {
    name: "LearningRoom",
    description: "LearningRoomDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper2",
    isBasic: true,
    level: 2,
  },
  {
    name: "JesterCastle",
    description: "JesterCastleDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper3",
    isBasic: true,
    level: 3,
  },
  {
    name: "MessyHouse",
    description: "MessyHouseDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper4",
    isBasic: true,
    level: 4,
  },
  {
    name: "Circus",
    description: "CircusDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper5",
    isBasic: true,
    level: 5,
  },
  {
    name: "PranksterCity",
    description: "PranksterCityDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper6",
    isBasic: true,
    level: 6,
  },
  {
    name: "EnchantedForest",
    description: "EnchantedForestDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper7",
    isBasic: true,
    level: 7,
  },
  {
    name: "TradingRoom",
    description: "TradingRoomDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper8",
    isBasic: true,
    level: 8,
  },
  {
    name: "SorcererHouse",
    description: "SorcererHouseDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper9",
    isBasic: true,
    level: 9,
  },
  {
    name: "MagicCastle",
    description: "MagicCastleDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper10",
    isBasic: true,
    level: 10,
  },
  {
    name: "NewYorkBasic",
    description: "NewYorkBasicDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper11",
    isBasic: true,
    level: 11,
  },
  {
    name: "MasterCastle",
    description: "MasterCastleDescription",
    category: ShopCategory.BACKGROUND,
    price: 0,
    image: "wallpaper12",
    isBasic: true,
    level: 12,
  },
  // Premium Wallpapers
  {
    name: "AfricanSavannah",
    description: "AfricanSavannahDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "africanSavannah",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "BeautifulBeach",
    description: "BeautifulBeachDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "beautifulBeach",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "BigTemple",
    description: "BigTempleDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "bigTemple",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "BlackHouse",
    description: "BlackHouseDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "blackHouse",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "BlockchainRoom",
    description: "BlockchainRoomDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "blockchainRoom",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "BotanicalGarden",
    description: "BotanicalGardenDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "botanicalGarden",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Casino",
    description: "CasinoDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "casino",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "ChemistryLab",
    description: "ChemistryLabDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "chemistryLab",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "CocktailBar",
    description: "CocktailBarDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "cocktailBar",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Desert",
    description: "DesertDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "desert",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "DesertedBeach",
    description: "DesertedBeachDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "desertedBeach",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "EntranceToTheTemple",
    description: "EntranceToTheTempleDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "entranceToTheTemple",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "GateOfTheNight",
    description: "GateOfTheNightDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "gateOfTheNight",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "IndianTemple",
    description: "IndianTempleDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "indianTemple",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Japan",
    description: "JapanDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "japan",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "LasVegas",
    description: "LasVegasDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "lasVegas",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "MagicCity",
    description: "MagicCityDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "magicCity",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Manor",
    description: "ManorDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "manor",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "MarioPalace",
    description: "MarioPalaceDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "marioPalace",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "MysteriousForest",
    description: "MysteriousForestDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "mysteriousForest",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "NewYork",
    description: "NewYorkDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "newYork",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "OldMarket",
    description: "OldMarketDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "oldMarket",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Paris",
    description: "ParisDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "paris",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "RoyalHouse",
    description: "RoyalHouseDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "royalHouse",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "Space",
    description: "SpaceDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "space",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "StarWars",
    description: "StarWarsDescription",
    category: ShopCategory.BACKGROUND,
    price: 500,
    image: "starWars",
    isBasic: false,
    invoiceUrl: "",
  },
  // Boosts
  {
    name: "OfflineBoost12h",
    description: "OfflineBoost12hDescription",
    category: ShopCategory.BOOST,
    price: 75,
    boostDuration: 12,
    boostType: "offline",
    image: "boost12h",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "OfflineBoost24h",
    description: "OfflineBoost24hDescription",
    category: ShopCategory.BOOST,
    price: 150,
    boostDuration: 24,
    boostType: "offline",
    image: "boost1day",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "OfflineBoost48h",
    description: "OfflineBoost48hDescription",
    category: ShopCategory.BOOST,
    price: 300,
    boostDuration: 48,
    boostType: "offline",
    image: "boost2day",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "OfflineBoost72h",
    description: "OfflineBoost72hDescription",
    category: ShopCategory.BOOST,
    price: 450,
    boostDuration: 72,
    boostType: "offline",
    image: "boost3day",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "OfflineBoost168h",
    description: "OfflineBoost168hDescription",
    category: ShopCategory.BOOST,
    price: 1000,
    boostDuration: 168,
    boostType: "offline",
    image: "boost1week",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "OfflineBoost12hReward",
    description: "OfflineBoost12hRewardDescription",
    category: ShopCategory.BOOST,
    price: 300,
    boostDuration: 12,
    boostType: "rewards",
    boostReward: 50,
    image: "boost12hReward",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "OfflineBoost24hReward",
    description: "OfflineBoost24hRewardDescription",
    category: ShopCategory.BOOST,
    price: 500,
    boostDuration: 24,
    boostType: "rewards",
    boostReward: 50,
    image: "boost1dayReward",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "OfflineBoost168hReward",
    description: "OfflineBoost168hRewardDescription",
    category: ShopCategory.BOOST,
    price: 2500,
    boostDuration: 168,
    boostType: "rewards",
    boostReward: 50,
    image: "boost1weekReward",
    isBasic: false,
    invoiceUrl: "",
  },
  // OTHERS - Friends
  {
    name: "friendOne",
    description: "friendOneDescription",
    category: ShopCategory.OTHERS,
    price: 50,
    image: "friendOne",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "friendThree",
    description: "friendThreeDescription",
    category: ShopCategory.OTHERS,
    price: 120,
    image: "friendThree",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "friendFive",
    description: "friendFiveDescription",
    category: ShopCategory.OTHERS,
    price: 175,
    image: "friendFive",
    isBasic: false,
    invoiceUrl: "",
  },
  {
    name: "friendTen",
    description: "friendTenDescription",
    category: ShopCategory.OTHERS,
    price: 300,
    image: "friendTen",
    isBasic: false,
    invoiceUrl: "",
  },
];
