export const upgradesData = [
  {
    name: "Jester's Hat",
    description: "Damn! This accessory doesn't add much since it's the hat Jok wears all the time!",
    image: 'jesterHat',
    baseCost: 1000,
    basePoints: 40,
    category: 'Accessory',
    subcategory: 'Hats',
    srNo: '1',
    src: 'Accessory/Hats/jester-hat.webp'
  },
  {
    name: 'Samurai Bandana',
    description: 'JOK is ready for war with this samurai bandana made of turtle hair',
    image: 'samuraiBandana',
    baseCost: 1130,
    basePoints: 44,
    category: 'Accessory',
    subcategory: 'Hats',
    srNo: '2',
    src: 'Accessory/Hats/samurai-bandana.webp'
  },
  {
    name: 'Sombrero',
    description: "JOK's sombrero allows him to attack stealthily even in very high temperatures.",
    image: 'sombrero',
    baseCost: 1290,
    basePoints: 55,
    category: 'Accessory',
    subcategory: 'Hats',
    srNo: '3',
    src: 'Accessory/Hats/sombrero.webp'
  },
  {
    name: 'Pirate Hat',
    description: 'JOK sparrow is back, pirates fear him to the depths of the oceans.',
    image: 'pirateHat',
    baseCost: 1180,
    basePoints: 51,
    category: 'Accessory',
    subcategory: 'Hats',
    srNo: '4',
    src: 'Accessory/Hats/pirate-hat.webp'
  },
  {
    name: "King's Crown",
    description: 'You always knew, there is room for only one King: JOK',
    image: 'kingCrown',
    baseCost: 1690,
    basePoints: 70,
    category: 'Accessory',
    subcategory: 'Hats',
    srNo: '5',
    src: 'Accessory/Hats/king-crown.webp'
  },
  {
    name: 'Inflatable Sumo Suit',
    description: 'Allows you to bounce off opponents.',
    image: 'sumoSuit',
    baseCost: 1580,
    basePoints: 52,
    category: 'Accessory',
    subcategory: 'Outfit',
    srNo: '6',
    src: 'Accessory/Outfit/sumo-suit.webp'
  },
  {
    name: 'Patchwork Invisibility Cloak',
    description: 'Makes one partially invisible, except for the seams.',
    image: 'invisibilityCloak',
    baseCost: 1590,
    basePoints: 56,
    category: 'Accessory',
    subcategory: 'Outfit',
    srNo: '7',
    src: 'Accessory/Outfit/invisibility-cloak.webp'
  },
  {
    name: 'Supersayan Costume',
    description: 'Jok increases his power and can temporarily blind enemies.',
    image: 'supersayan',
    baseCost: 1510,
    basePoints: 58,
    category: 'Accessory',
    subcategory: 'Outfit',
    srNo: '8',
    src: 'Accessory/Outfit/supersayan.webp'
  },
  {
    name: 'Broken Robot Costume',
    description: 'Articulated arms and legs with fake cables and sparks.',
    image: 'brokenRobot',
    baseCost: 1610,
    basePoints: 48,
    category: 'Accessory',
    subcategory: 'Outfit',
    srNo: '9',
    src: 'Accessory/Outfit/broken-robot.webp'
  },
  {
    name: 'Electric Toga',
    description: 'Generates a small electric field to keep curious people away.',
    image: 'electricToga',
    baseCost: 1720,
    basePoints: 69,
    category: 'Accessory',
    subcategory: 'Outfit',
    srNo: '10',
    src: 'Accessory/Outfit/electric-toga.webp'
  },
  {
    name: 'Sound Lightsaber',
    description: 'Changes color and makes funny sounds with each movement.',
    image: 'lightSaber',
    baseCost: 1840,
    basePoints: 70,
    category: 'Accessory',
    subcategory: 'Weapons',
    srNo: '11',
    src: 'Accessory/Weapons/lightsaber.webp'
  },
  {
    name: 'Katana',
    description: 'Ready to cut up your opponents, the katana is the perfect tool to attack discreetly.',
    image: 'katana',
    baseCost: 1920,
    basePoints: 88,
    category: 'Accessory',
    subcategory: 'Weapons',
    srNo: '12',
    src: 'Accessory/Weapons/katana.webp'
  },
  {
    name: 'Giant Rubber Hammer',
    description: 'Bounces off surfaces and can send JOK flying back.',
    image: 'rubberHammer',
    baseCost: 1810,
    basePoints: 75,
    category: 'Accessory',
    subcategory: 'Weapons',
    srNo: '13',
    src: 'Accessory/Weapons/rubber-hammer.webp'
  },
  {
    name: 'Machine Gun',
    description: "Even with blanks, JOK's machine gun sends funny bullets miles away.",
    image: 'machinesgun',
    baseCost: 2030,
    basePoints: 83,
    category: 'Accessory',
    subcategory: 'Weapons',
    srNo: '14',
    src: 'Accessory/Weapons/machinesgun.webp'
  },
  {
    name: 'Bazooka',
    description: 'Launches intercontinental rockets to trap opponents.',
    image: 'bazooka',
    baseCost: 2240,
    basePoints: 105,
    category: 'Accessory',
    subcategory: 'Weapons',
    srNo: '15',
    src: 'Accessory/Weapons/bazooka.webp'
  },
  {
    name: 'Spring Boots',
    description: 'Allows you to jump very high, with an always unpredictable landing.',
    image: 'springBoots',
    baseCost: 2390,
    basePoints: 102,
    category: 'Accessory',
    subcategory: 'Various accessories',
    srNo: '16',
    src: 'Accessory/Various-accesoires/spring-boots.webp'
  },
  {
    name: 'Squeaky Boxing Gloves',
    description: 'Makes a squeaky sound with each punch.',
    image: 'boxingGloves',
    baseCost: 2420,
    basePoints: 109,
    category: 'Accessory',
    subcategory: 'Various accessories',
    srNo: '17',
    src: 'Accessory/Various-accesoires/boxing-gloves.webp'
  },
  {
    name: 'Fancy Gadget Belt',
    description: 'Equipped with useless but fun gadgets like a hand crank fan, cuckoo clock, etc.',
    image: 'fancyGadgetBelt',
    baseCost: 2350,
    basePoints: 104,
    category: 'Accessory',
    subcategory: 'Various accessories',
    srNo: '18',
    src: 'Accessory/Various-accesoires/fancy-gadget-belt.webp'
  },
  {
    name: 'Placebo X-ray Glasses',
    description: 'Claim to give the ability to see through walls, but work randomly.',
    image: 'placeboXrayGlasses',
    baseCost: 2450,
    basePoints: 106,
    category: 'Accessory',
    subcategory: 'Various accessories',
    srNo: '19',
    src: 'Accessory/Various-accesoires/placebo-X-ray-glasses.webp'
  },
  {
    name: 'Helicopter Backpack',
    description: 'For a chaotic and short flight.',
    image: 'helicopterBackpack',
    baseCost: 2510,
    basePoints: 112,
    category: 'Accessory',
    subcategory: 'Various accessories',
    srNo: '20',
    src: 'Accessory/Various-accesoires/helicopter-backpack.webp'
  },
  // Skills
  {
    name: 'Strength',
    description: 'Ability to exert physical power.',
    image: 'strength',
    baseCost: 2380,
    basePoints: 125,
    category: 'Skills',
    subcategory: 'Physical Skills',
    srNo: '21',
    src: 'Skills/Physical-Skills/strength.webp'
  },
  {
    name: 'Agility',
    description: 'Ability to move quickly and accurately.',
    image: 'agility',
    baseCost: 2490,
    basePoints: 128,
    category: 'Skills',
    subcategory: 'Physical Skills',
    srNo: '22',
    src: 'Skills/Physical-Skills/agility.webp'
  },
  {
    name: 'Endurance',
    description: 'Resistance to prolonged effort.',
    image: 'endurance',
    baseCost: 2370,
    basePoints: 132,
    category: 'Skills',
    subcategory: 'Physical Skills',
    srNo: '23',
    src: 'Skills/Physical-Skills/endurance.webp'
  },
  {
    name: 'Speed',
    description: 'Speed in movements.',
    image: 'speed',
    baseCost: 2710,
    basePoints: 134,
    category: 'Skills',
    subcategory: 'Physical Skills',
    srNo: '24',
    src: 'Skills/Physical-Skills/speed.webp'
  },
  {
    name: 'Resistance',
    description: 'Ability to withstand blows or extreme conditions.',
    image: 'resistance',
    baseCost: 2820,
    basePoints: 138,
    category: 'Skills',
    subcategory: 'Physical Skills',
    srNo: '25',
    src: 'Skills/Physical-Skills/resistance.webp'
  },
  {
    name: 'Accuracy',
    description: 'Ability to hit targets accurately.',
    image: 'accuracy',
    baseCost: 2750,
    basePoints: 136,
    category: 'Skills',
    subcategory: 'Physical Skills',
    srNo: '26',
    src: 'Skills/Physical-Skills/accuracy.webp'
  },
  {
    name: 'Balance',
    description: 'Ability to maintain stability under difficult conditions.',
    image: 'balance',
    baseCost: 3140,
    basePoints: 143,
    category: 'Skills',
    subcategory: 'Physical Skills',
    srNo: '27',
    src: 'Skills/Physical-Skills/balance.webp'
  },
  {
    name: 'Coordination',
    description: 'Ability to synchronize movements effectively.',
    image: 'coordination',
    baseCost: 3040,
    basePoints: 147,
    category: 'Skills',
    subcategory: 'Physical Skills',
    srNo: '28',
    src: 'Skills/Physical-Skills/coordination.webp'
  },
  {
    name: 'Intelligence',
    description: 'Ability to solve complex problems.',
    image: 'intelligence',
    baseCost: 2810,
    basePoints: 135,
    category: 'Skills',
    subcategory: 'Mental Skills',
    srNo: '29',
    src: 'Skills/Mental-Skills/intelligence.webp'
  },
  {
    name: 'Wisdom',
    description: 'Informed judgment and decision-making.',
    image: 'wisdom',
    baseCost: 3330,
    basePoints: 146,
    category: 'Skills',
    subcategory: 'Mental Skills',
    srNo: '30',
    src: 'Skills/Mental-Skills/wisdom.webp'
  },
  {
    name: 'Maturity',
    description: 'Ability to handle emotions and difficult situations.',
    image: 'maturity',
    baseCost: 3220,
    basePoints: 142,
    category: 'Skills',
    subcategory: 'Mental Skills',
    srNo: '31',
    src: 'Skills/Mental-Skills/maturity.webp'
  },
  {
    name: 'Concentration',
    description: 'Ability to stay focused on a task.',
    image: 'concentration',
    baseCost: 3570,
    basePoints: 149,
    category: 'Skills',
    subcategory: 'Mental Skills',
    srNo: '32',
    src: 'Skills/Mental-Skills/concentration.webp'
  },
  {
    name: 'Memory',
    description: 'Ability to remember important information.',
    image: 'memory',
    baseCost: 3450,
    basePoints: 148,
    category: 'Skills',
    subcategory: 'Mental Skills',
    srNo: '33',
    src: 'Skills/Mental-Skills/memory.webp'
  },
  {
    name: 'Logic',
    description: 'Ability to think in a structured and rational way.',
    image: 'logic',
    baseCost: 3430,
    basePoints: 144,
    category: 'Skills',
    subcategory: 'Mental Skills',
    srNo: '34',
    src: 'Skills/Mental-Skills/logic.webp'
  },
  {
    name: 'Intuition',
    description: 'Ability to understand or anticipate situations without direct evidence.',
    image: 'intuition',
    baseCost: 3610,
    basePoints: 150,
    category: 'Skills',
    subcategory: 'Mental Skills',
    srNo: '35',
    src: 'Skills/Mental-Skills/intuition.webp'
  },
  {
    name: 'Creativity',
    description: 'Ability to think outside the box and find innovative solutions.',
    image: 'creativity',
    baseCost: 3850,
    basePoints: 156,
    category: 'Skills',
    subcategory: 'Mental Skills',
    srNo: '36',
    src: 'Skills/Mental-Skills/creativity.webp'
  },
  {
    name: 'Charisma',
    description: 'Ability to influence and inspire others.',
    image: 'charisma',
    baseCost: 3620,
    basePoints: 152,
    category: 'Skills',
    subcategory: 'Social Skills',
    srNo: '37',
    src: 'Skills/Social-Skills/charisma.webp'
  },
  {
    name: 'Leadership',
    description: 'Ability to lead a group effectively.',
    image: 'leadership',
    baseCost: 3760,
    basePoints: 157,
    category: 'Skills',
    subcategory: 'Social Skills',
    srNo: '38',
    src: 'Skills/Social-Skills/leadership.webp'
  },
  {
    name: 'Persuasion',
    description: 'Ability to convince others.',
    image: 'persuasion',
    baseCost: 3530,
    basePoints: 159,
    category: 'Skills',
    subcategory: 'Social Skills',
    srNo: '39',
    src: 'Skills/Social-Skills/persuasion.webp'
  },
  {
    name: 'Empathy',
    description: 'Ability to understand and share the feelings of others.',
    image: 'empathy',
    baseCost: 3430,
    basePoints: 157,
    category: 'Skills',
    subcategory: 'Social Skills',
    srNo: '40',
    src: 'Skills/Social-Skills/empathy.webp'
  },
  {
    name: 'Communication',
    description: 'Ability to convey information clearly.',
    image: 'communication',
    baseCost: 3750,
    basePoints: 164,
    category: 'Skills',
    subcategory: 'Social Skills',
    srNo: '41',
    src: 'Skills/Social-Skills/communication.webp'
  },
  {
    name: 'Negotiation',
    description: 'Ability to find a compromise or resolve conflicts.',
    image: 'negotiation',
    baseCost: 3910,
    basePoints: 163,
    category: 'Skills',
    subcategory: 'Social Skills',
    srNo: '42',
    src: 'Skills/Social-Skills/negotiation.webp'
  },
  {
    name: 'Diplomacy',
    description: 'Ability to manage relationships with tact and finesse.',
    image: 'diplomacy',
    baseCost: 3860,
    basePoints: 165,
    category: 'Skills',
    subcategory: 'Social Skills',
    srNo: '43',
    src: 'Skills/Social-Skills/diplomacy.webp'
  },
  {
    name: 'Translation',
    description: 'Ability to understand and speak multiple languages.',
    image: 'translation',
    baseCost: 3980,
    basePoints: 177,
    category: 'Skills',
    subcategory: 'Social Skills',
    srNo: '44',
    src: 'Skills/Social-Skills/translation.webp'
  },
  {
    name: 'Weapon Mastery',
    description: 'Ability to wield different weapons with expertise.',
    image: 'weaponMastery',
    baseCost: 3950,
    basePoints: 160,
    category: 'Skills',
    subcategory: 'Technical Skills',
    srNo: '45',
    src: 'Skills/Technical-Skills/weapon-mastery.webp'
  },
  {
    name: 'Computer Science',
    description: 'Technology and programming skills.',
    image: 'information',
    baseCost: 4020,
    basePoints: 171,
    category: 'Skills',
    subcategory: 'Technical Skills',
    srNo: '46',
    src: 'Skills/Technical-Skills/information.webp'
  },
  {
    name: 'Piloting',
    description: 'Ability to pilot vehicles or machines.',
    image: 'piloting',
    baseCost: 4010,
    basePoints: 165,
    category: 'Skills',
    subcategory: 'Technical Skills',
    srNo: '47',
    src: 'Skills/Technical-Skills/piloting.webp'
  },
  {
    name: 'Engineering',
    description: 'Skill in designing, building or repairing machines.',
    image: 'engineering',
    baseCost: 4070,
    basePoints: 168,
    category: 'Skills',
    subcategory: 'Technical Skills',
    srNo: '48',
    src: 'Skills/Technical-Skills/engineering.webp'
  },
  {
    name: 'Crafting',
    description: 'Talent for creating useful or aesthetic objects.',
    image: 'crafting',
    baseCost: 4090,
    basePoints: 168,
    category: 'Skills',
    subcategory: 'Technical Skills',
    srNo: '49',
    src: 'Skills/Technical-Skills/crafting.webp'
  },
  {
    name: 'Detection',
    description: 'Ability to spot traps, secrets or anomalies.',
    image: 'detection',
    baseCost: 4120,
    basePoints: 172,
    category: 'Skills',
    subcategory: 'Technical Skills',
    srNo: '50',
    src: 'Skills/Technical-Skills/detection.webp'
  },
  {
    name: 'Chemistry',
    description: 'Skill in handling chemicals or potions.',
    image: 'chemistry',
    baseCost: 4110,
    basePoints: 170,
    category: 'Skills',
    subcategory: 'Technical Skills',
    srNo: '51',
    src: 'Skills/Technical-Skills/chemistry.webp'
  },
  {
    name: 'Survival',
    description: 'Skill to live in hostile environments.',
    image: 'survival',
    baseCost: 4140,
    basePoints: 188,
    category: 'Skills',
    subcategory: 'Technical Skills',
    srNo: '52',
    src: 'Skills/Technical-Skills/survival.webp'
  },
  {
    name: 'Elemental Control',
    description: 'Ability to manipulate fire, water, air or earth.',
    image: 'elementalControl',
    baseCost: 4160,
    basePoints: 177,
    category: 'Skills',
    subcategory: 'Magical Skills',
    srNo: '53',
    src: 'Skills/Magical-Skills/elemental-control.webp'
  },
  {
    name: 'Telekinesis',
    description: 'Power to move objects with thought.',
    image: 'telekinesis',
    baseCost: 4200,
    basePoints: 175,
    category: 'Skills',
    subcategory: 'Magical Skills',
    srNo: '54',
    src: 'Skills/Magical-Skills/telekinesis.webp'
  },
  {
    name: 'Healing',
    description: 'Ability to heal injuries or diseases.',
    image: 'healing',
    baseCost: 4370,
    basePoints: 178,
    category: 'Skills',
    subcategory: 'Magical Skills',
    srNo: '55',
    src: 'Skills/Magical-Skills/healing.webp'
  },
  {
    name: 'Invisibility',
    description: 'Ability to make oneself invisible to others.',
    image: 'invisibility',
    baseCost: 4430,
    basePoints: 189,
    category: 'Skills',
    subcategory: 'Magical Skills',
    srNo: '56',
    src: 'Skills/Magical-Skills/invisibility.webp'
  },
  {
    name: 'Necromancy',
    description: 'Power to control the dead or spirits.',
    image: 'necromancy',
    baseCost: 4370,
    basePoints: 186,
    category: 'Skills',
    subcategory: 'Magical Skills',
    srNo: '57',
    src: 'Skills/Magical-Skills/necromancy.webp'
  },
  {
    name: 'Summoning',
    description: 'Ability to call creatures or objects using magic.',
    image: 'summoning',
    baseCost: 4390,
    basePoints: 185,
    category: 'Skills',
    subcategory: 'Magical Skills',
    srNo: '58',
    src: 'Skills/Magical-Skills/summoning.webp'
  },
  {
    name: 'Pre-cognition',
    description: 'Ability to see or predict the future.',
    image: 'preCognition',
    baseCost: 4480,
    basePoints: 210,
    category: 'Skills',
    subcategory: 'Magical Skills',
    srNo: '59',
    src: 'Skills/Magical-Skills/pre-cognition.webp'
  },
  {
    name: 'Enchantment',
    description: 'Ability to imbue objects with magical powers.',
    image: 'enchantement',
    baseCost: 4610,
    basePoints: 255,
    category: 'Skills',
    subcategory: 'Magical Skills',
    srNo: '60',
    src: 'Skills/Magical-Skills/enchantement.webp'
  },
  // Business
  {
    name: 'MEV Bot',
    description: 'Invest in bots that exploit price differences on blockchains to make profits.',
    image: 'mevBot',
    baseCost: 4550,
    basePoints: 232,
    category: 'Business',
    subcategory: 'Cryptocurrency',
    srNo: '61',
    src: 'Business/Cryptocurrency/mev-bot.webp'
  },
  {
    name: 'Meme Coins',
    description: 'Create and manage a new virtual currency based on popular Internet phenomena.',
    image: 'memecoin',
    baseCost: 4640,
    basePoints: 235,
    category: 'Business',
    subcategory: 'Cryptocurrency',
    srNo: '62',
    src: 'Business/Cryptocurrency/memecoin.webp'
  },
  {
    name: 'Mining Farm',
    description: 'Build and upgrade a farm to mine cryptocurrencies more efficiently.',
    image: 'miningFarm',
    baseCost: 4650,
    basePoints: 243,
    category: 'Business',
    subcategory: 'Cryptocurrency',
    srNo: '63',
    src: 'Business/Cryptocurrency/mining-farm.webp'
  },
  {
    name: 'Crypto Exchange Platform',
    description: 'Launch and develop a platform for trading cryptocurrencies.',
    image: 'cryptoExchangePlatform',
    baseCost: 4710,
    basePoints: 254,
    category: 'Business',
    subcategory: 'Cryptocurrency',
    srNo: '64',
    src: 'Business/Cryptocurrency/crypto-exchange-platform.webp'
  },
  {
    name: 'Secure Crypto Wallet',
    description: 'Development of a digital wallet application with advanced security features.',
    image: 'cryptoWallet',
    baseCost: 4830,
    basePoints: 262,
    category: 'Business',
    subcategory: 'Cryptocurrency',
    srNo: '65',
    src: 'Business/Cryptocurrency/crypto-wallet.webp'
  },
  {
    name: 'Building Construction',
    description: 'Planning, building and managing a residential or commercial building.',
    image: 'buildingConstruction',
    baseCost: 4730,
    basePoints: 255,
    category: 'Business',
    subcategory: 'Real Estate',
    srNo: '66',
    src: 'Business/Real-Estate/building-construction.webp'
  },
  {
    name: 'Hotel Renovation',
    description: 'Purchase and renovate hotels to increase their value and profitability.',
    image: 'hotelRenovation',
    baseCost: 4820,
    basePoints: 257,
    category: 'Business',
    subcategory: 'Real Estate',
    srNo: '67',
    src: 'Business/Real-Estate/hotel-renovation.webp'
  },
  {
    name: 'Resort Development',
    description: 'Creation and expansion of resorts in exotic locations.',
    image: 'resortDevelopment',
    baseCost: 4810,
    basePoints: 258,
    category: 'Business',
    subcategory: 'Real Estate',
    srNo: '68',
    src: 'Business/Real-Estate/resort-development.webp'
  },
  {
    name: 'Real Estate Agency',
    description: 'Creation of an agency to buy, sell and rent properties.',
    image: 'realEstateAgency',
    baseCost: 4740,
    basePoints: 258,
    category: 'Business',
    subcategory: 'Real Estate',
    srNo: '69',
    src: 'Business/Real-Estate/real-estate-agency.webp'
  },
  {
    name: 'Virtual Reality Startup',
    description: 'Development of games, educational applications or immersive experiences in VR.',
    image: 'vr',
    baseCost: 4920,
    basePoints: 263,
    category: 'Business',
    subcategory: 'Technology',
    srNo: '70',
    src: 'Business/Technology/vr.webp'
  },
  {
    name: 'Cybersecurity Firm',
    description: 'Setting up and expanding a company specializing in data protection.',
    image: 'cybersecurity',
    baseCost: 5020,
    basePoints: 264,
    category: 'Business',
    subcategory: 'Technology',
    srNo: '71',
    src: 'Business/Technology/cybersecurity.webp'
  },
  {
    name: 'Software Development',
    description: 'Creation and sale of custom software for various industries.',
    image: 'softwareDevelopment',
    baseCost: 5070,
    basePoints: 268,
    category: 'Business',
    subcategory: 'Technology',
    srNo: '72',
    src: 'Business/Technology/software-development.webp'
  },
  {
    name: 'Gadget Production',
    description: 'Design and manufacture of innovative technological gadgets.',
    image: 'gadgetProduction',
    baseCost: 5120,
    basePoints: 274,
    category: 'Business',
    subcategory: 'Technology',
    srNo: '73',
    src: 'Business/Technology/gadget-production.webp'
  },
  {
    name: 'AI Research Lab',
    description: 'Investment in research and development of artificial intelligence.',
    image: 'aiResearch',
    baseCost: 5120,
    basePoints: 282,
    category: 'Business',
    subcategory: 'Technology',
    srNo: '74',
    src: 'Business/Technology/ai-research.webp'
  },
  {
    name: 'Film Studio',
    description: 'Production and distribution of films and television series.',
    image: 'filmStudio',
    baseCost: 5030,
    basePoints: 273,
    category: 'Business',
    subcategory: 'Entertainment',
    srNo: '75',
    src: 'Business/Entertainment/film-studio.webp'
  },
  {
    name: 'Amusement Park',
    description: 'Creation and management of a park with various attractions and shows.',
    image: 'amusementPark',
    baseCost: 5080,
    basePoints: 274,
    category: 'Business',
    subcategory: 'Entertainment',
    srNo: '76',
    src: 'Business/Entertainment/amusement-park.webp'
  },
  {
    name: 'Music Label',
    description: 'Start a label to produce and promote artists.',
    image: 'musicLabel',
    baseCost: 5150,
    basePoints: 266,
    category: 'Business',
    subcategory: 'Entertainment',
    srNo: '77',
    src: 'Business/Entertainment/music-label.webp'
  },
  {
    name: 'Digital Marketing Agency',
    description: 'Online promotion strategies for brands and celebrities.',
    image: 'digitalMarketingAgency',
    baseCost: 5170,
    basePoints: 270,
    category: 'Business',
    subcategory: 'Entertainment',
    srNo: '78',
    src: 'Business/Entertainment/digital-marketing-agency.webp'
  },
  {
    name: 'Music Festival',
    description: 'Organization and expansion of annual festivals with international artists.',
    image: 'musicFestival',
    baseCost: 5250,
    basePoints: 288,
    category: 'Business',
    subcategory: 'Entertainment',
    srNo: '79',
    src: 'Business/Entertainment/music-festival.webp'
  },
  {
    name: 'Themed Fast Food Chain',
    description: 'Launch and expand a fast food chain with a unique concept.',
    image: 'fastFood',
    baseCost: 5220,
    basePoints: 265,
    category: 'Business',
    subcategory: 'Restoration',
    srNo: '80',
    src: 'Business/Restoration/fast-food.webp'
  },
  {
    name: 'Craft Brewery',
    description: 'Production and distribution of craft beers.',
    image: 'brewery',
    baseCost: 5380,
    basePoints: 282,
    category: 'Business',
    subcategory: 'Restoration',
    srNo: '81',
    src: 'Business/Restoration/brewery.webp'
  },
  {
    name: 'Fine Dining Restaurant',
    description: 'Open and manage a fine dining restaurant.',
    image: 'restaurant',
    baseCost: 5350,
    basePoints: 280,
    category: 'Business',
    subcategory: 'Restoration',
    srNo: '82',
    src: 'Business/Restoration/restaurant.webp'
  },
  {
    name: 'Innovative Food Truck',
    description: 'Development of a food truck offering fusion or experimental cuisine.',
    image: 'foodTruck',
    baseCost: 5440,
    basePoints: 287,
    category: 'Business',
    subcategory: 'Restoration',
    srNo: '83',
    src: 'Business/Restoration/food-truck.webp'
  },
  {
    name: 'Cooking School',
    description: 'Creation of a school to train chefs and cooking enthusiasts.',
    image: 'cookingSchool',
    baseCost: 5700,
    basePoints: 295,
    category: 'Business',
    subcategory: 'Restoration',
    srNo: '84',
    src: 'Business/Restoration/cooking-school.webp'
  },
  // Lifestyle
  {
    name: 'Private Jet',
    description: 'Ultra-luxury jet with onboard spa and private suites.',
    image: 'privateJet',
    baseCost: 6300,
    basePoints: 314,
    category: 'Lifestyle',
    subcategory: 'Transportation',
    srNo: '85',
    src: 'Lifestyle/Transportation/private-jet.webp'
  },
  {
    name: 'Helicopter',
    description: 'VIP helicopter with lounge area and personal pilot.',
    image: 'helicopter',
    baseCost: 6500,
    basePoints: 330,
    category: 'Lifestyle',
    subcategory: 'Transportation',
    srNo: '86',
    src: 'Lifestyle/Transportation/helicopter.webp'
  },
  {
    name: 'Luxury Yacht',
    description: 'Superyacht with swimming pool, onboard cinema and helipad.',
    image: 'yacht',
    baseCost: 6600,
    basePoints: 332,
    category: 'Lifestyle',
    subcategory: 'Transportation',
    srNo: '87',
    src: 'Lifestyle/Transportation/yacht.webp'
  },
  {
    name: 'Sports Car',
    description: 'Limited Edition Hypercar with Extreme Performance.',
    image: 'sportsCar',
    baseCost: 6940,
    basePoints: 347,
    category: 'Lifestyle',
    subcategory: 'Transportation',
    srNo: '88',
    src: 'Lifestyle/Transportation/sports-car.webp'
  },
  {
    name: 'Luxury Watch',
    description: 'Personalized access to new collections before their release.',
    image: 'luxuryWatch',
    baseCost: 7900,
    basePoints: 386,
    category: 'Lifestyle',
    subcategory: 'Accessories',
    srNo: '89',
    src: 'Lifestyle/Accessories/luxury-watch.webp'
  },
  {
    name: 'Haute Couture Clothing Collection',
    description: 'Exclusive designer clothing collection tailored to your preferences.',
    image: 'couture',
    baseCost: 8300,
    basePoints: 410,
    category: 'Lifestyle',
    subcategory: 'Accessories',
    srNo: '90',
    src: 'Lifestyle/Accessories/couture.webp'
  },
  {
    name: 'Extravagant Jewelry',
    description: 'A complete set of personalized jewelry from a renowned jeweler.',
    image: 'jewelry',
    baseCost: 8200,
    basePoints: 402,
    category: 'Lifestyle',
    subcategory: 'Accessories',
    srNo: '91',
    src: 'Lifestyle/Accessories/jewelry.webp'
  },
  {
    name: 'Artworks',
    description: 'Exclusive artwork purchased at a prestigious auction.',
    image: 'art',
    baseCost: 8500,
    basePoints: 425,
    category: 'Lifestyle',
    subcategory: 'Accessories',
    srNo: '92',
    src: 'Lifestyle/Accessories/art.webp'
  },
  {
    name: 'Villa',
    description: 'Ultra-luxury villa with dedicated staff and private beach.',
    image: 'villa',
    baseCost: 8200,
    basePoints: 412,
    category: 'Lifestyle',
    subcategory: 'Holidays & Property',
    srNo: '93',
    src: 'Lifestyle/Holidays-Property/villa.webp'
  },
  {
    name: 'Private Islands',
    description: 'Own an entire island with luxury facilities.',
    image: 'privateIslands',
    baseCost: 8400,
    basePoints: 430,
    category: 'Lifestyle',
    subcategory: 'Holidays & Property',
    srNo: '94',
    src: 'Lifestyle/Holidays-Property/private-islands.webp'
  },
  {
    name: 'Mountain Chalet',
    description: 'Exclusive chalet with concierge service and private helicopter for access.',
    image: 'mountainChalet',
    baseCost: 8600,
    basePoints: 443,
    category: 'Lifestyle',
    subcategory: 'Holidays & Property',
    srNo: '95',
    src: 'Lifestyle/Holidays-Property/mountain-chalet.webp'
  },
  {
    name: 'VIP Safari',
    description: 'Exclusive safari with accommodation in a private reserve.',
    image: 'safari',
    baseCost: 8800,
    basePoints: 455,
    category: 'Lifestyle',
    subcategory: 'Holidays & Property',
    srNo: '96',
    src: 'Lifestyle/Holidays-Property/safari.webp'
  },
  {
    name: 'Participation in a Formula 1 Grand Prix',
    description: 'Drive a Formula 1 car on a famous circuit.',
    image: 'formula',
    baseCost: 9300,
    basePoints: 467,
    category: 'Lifestyle',
    subcategory: 'Exclusive Experience',
    srNo: '97',
    src: 'Lifestyle/Exclusive-Experience/formula.webp'
  },
  {
    name: 'Space Expedition',
    description: 'Stay in a commercial space station.',
    image: 'spaceExpedition',
    baseCost: 9800,
    basePoints: 480,
    category: 'Lifestyle',
    subcategory: 'Exclusive Experience',
    srNo: '98',
    src: 'Lifestyle/Exclusive-Experience/space-expedition.webp'
  },
  {
    name: 'Dinner with a Star Chef',
    description: 'Star Chef cooking a private meal at your home.',
    image: 'restaurantChef',
    baseCost: 10500,
    basePoints: 538,
    category: 'Lifestyle',
    subcategory: 'Exclusive Experience',
    srNo: '99',
    src: 'Lifestyle/Exclusive-Experience/restaurant.webp'
  },
  {
    name: 'Underwater Treasure Hunt',
    description: 'Private expedition with cutting-edge equipment and expert researchers.',
    image: 'underwaterTreasureHunt',
    baseCost: 10400,
    basePoints: 526,
    category: 'Lifestyle',
    subcategory: 'Exclusive Experience',
    srNo: '100',
    src: 'Lifestyle/Exclusive-Experience/underwater-treasure-hunt.webp'
  },
  {
    name: 'Private Jet World Tour',
    description: 'World Tour with Custom Itinerary, Hotels and VIP Experiences.',
    image: 'privateTour',
    baseCost: 12900,
    basePoints: 777,
    category: 'Lifestyle',
    subcategory: 'Exclusive Experience',
    srNo: '101',
    src: 'Lifestyle/Exclusive-Experience/private-tour.webp'
  }
];
